from django.urls import path
from . import views

urlpatterns=[path('',views.index, name='index'),
             path('portfolio_details/',views.portfolio_details, name='portfolio_details'),
             path('service_details/',views.service_details, name='service_details'),
             path('work_permits/',views.work_permits, name='work_permits'),
             path('class_A/',views.class_A, name='class_A'),
             path('class_B/',views.class_B, name='class_B'),
             path('class_C/',views.class_C, name='class_C'),
             path('class_D/',views.class_D, name='class_D'),
             path('class_F/',views.class_F, name='class_F'),
             path('class_G/',views.class_G, name='class_G'),
             path('class_I/',views.class_I, name='class_I'),
             path('class_K/',views.class_K, name='class_K'),
             path('class_M/',views.class_M, name='class_M'),
             path('immigration_services/',views.immigration_services, name='immigration_services'),
             path('marriage_services/',views.marriage_services, name='marriage_services'),
             path('birth_certificates/',views.birth_certificates, name='birth_certificates'),
             path('deed_poll/',views.deed_poll, name='deed_poll'),
             path('brs/',views.brs, name='brs'),
             path('conveyancing/',views.conveyancing, name='conveyancing'),
             path('driving_license/',views.driving_license, name='driving_license'),
             path('eta/',views.eta, name='eta'),
             path('application_of_kenyan/',views.application_of_kenyan, name='application_of_kenyan'),
             path('declaration_of_dual/',views.declaration_of_dual, name='declaration_of_dual'),
             path('dependent_pass/',views.dependent_pass, name='dependent_pass'),
             path('first_time/',views.first_time, name='first_time'),
             path('internship_pass/',views.internship_pass, name='internship_pass'),
             path('interstate_pass/',views.interstate_pass, name='interstate_pass'),
             path('passport_renewal/',views.passport_renewal, name='passport_renewal'),
             path('permanent_residency/',views.permanent_residency, name='permanent_residency'),
             path('regaining_citizenship/',views.regaining_citizenship, name='regaining_citizenship'),
             path('special_pass/',views.special_pass, name='special_pass'),
             path('student_pass/',views.student_pass, name='student_pass'),
             path('visa_application/',views.visa_application, name='visa_application'),
             path('visa_extension/',views.visa_extension, name='visa_extension'),
             path('contact/',views.contact_view,name='contact'),
]